# Hyperparameter optimization configuration for Phase 4
# Defines the parameter grid to search during optimization

# Base name for experiments
base_name: "hparam_opt"

# Random seeds to use
seeds: [42, 43]

# Parameter grid to search
param_grid:
  # Learning rates to try
  "training.learning_rate": [1.0e-5, 2.0e-5, 5.0e-5]
  
  # Loss weights to try
  "training.loss_weights.classification": [0.5, 1.0, 2.0]
  "training.loss_weights.language": [0.5, 1.0, 2.0]
  
  # Training stages to try
  "training.three_stage.stage2.start_epoch": [3, 6, 9]
  "training.three_stage.stage2.lr_multiplier": [0.005, 0.01, 0.02]
  
  # Optimizer configurations
  "training.optimizer.weight_decay": [0.01, 0.001]
  
  # Batch size
  "data.batch_size": [8, 16, 32]

# Evaluation metrics to prioritize
priority_metrics:
  - classification_accuracy  # Primary classification metric
  - generation_bleu         # Primary generation metric
  - generation_rouge1_f     # Secondary generation metric