# Configuration for Question Classifier

# Model configuration
model:
  name: "ModernBert-base"
  custom_path: "/home/jovyan/nfs_share/models/huggingface/hub/ModernBERT-base"
  use_custom_path: true
  hidden_size: 768
  num_classes: 5
  dropout_rate: 0.1

# Training configuration
training:
  batch_size: 16
  num_epochs: 5
  learning_rate: 2.0e-5
  weight_decay: 0.01
  warmup_steps: 100
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  lr_scheduler_type: "cosine"
  num_workers: 1
  
# Data configuration
data:
  data_dir: "data/question_data"
  max_length: 128
  tokenizer_name: "ModernBert-base"

# Output configuration
output:
  model_dir: "models/question_classifier"
  log_steps: 100
  save_steps: 500
  eval_steps: 500

# Reproducibility configuration
reproducibility:
  seed: 42